pub const GENRE_OTHER: u8 = 12;

pub const GENRES: &[&str] = &[
    "Blues",
    "Classic Rock",
    "Country",
    "Dance",
    "Disco",
    "Funk",
    "Grunge",
    "Hip-Hop",
    "Jazz",
    "Metal",
    "New Age",
    "Oldies",
    "Other",
    "Pop",
    "R&B",
    "Rap",
    "Reggae",
    "Rock",
    "Techno",
    "Industrial",
    "Alternative",
    "Ska",
    "Death Metal",
    "Pranks",
    "Soundtrack",
    "Euro-Techno",
    "Ambient",
    "Trip-Hop",
    "Vocal",
    "Jazz+Funk",
    "Fusion",
    "Trance",
    "Classical",
    "Instrumental",
    "Acid",
    "House",
    "Game",
    "Sound Clip",
    "Gospel",
    "Noise",
    "AlternRock",
    "Bass",
    "Soul",
    "Punk",
    "Space",
    "Meditative",
    "Instrumental Pop",
    "Instrumental Rock",
    "Ethnic",
    "Gothic",
    "Darkwave",
    "Techno-Industrial",
    "Electronic",
    "Pop-Folk",
    "Eurodance",
    "Dream",
    "Southern Rock",
    "Comedy",
    "Cult",
    "Gangsta",
    "Top 40",
    "Christian Rap",
    "Pop/Funk",
    "Jungle",
    "Native American",
    "Cabaret",
    "New Wave",
    "Psychadelic",
    "Rave",
    "Showtunes",
    "Trailer",
    "Lo-Fi",
    "Tribal",
    "Acid Punk",
    "Acid Jazz",
    "Polka",
    "Retro",
    "Musical",
    "Rock & Roll",
    "Hard Rock",
    // Winamp extensions
    "Folk",
    "Folk-Rock",
    "National Folk",
    "Swing",
    "Fast Fusion",
    "Bebob",
    "Latin",
    "Revival",
    "Celtic",
    "Bluegrass",
    "Avantgarde",
    "Gothic Rock",
    "Progressive Rock",
    "Psychedelic Rock",
    "Symphonic Rock",
    "Slow Rock",
    "Big Band",
    "Chorus",
    "Easy Listening",
    "Acoustic",
    "Humour",
    "Speech",
    "Chanson",
    "Opera",
    "Chamber Music",
    "Sonata",
    "Symphony",
    "Booty Bass",
    "Primus",
    "Porn Groove",
    "Satire",
    "Slow Jam",
    "Club",
    "Tango",
    "Samba",
    "Folklore",
    "Ballad",
    "Power Ballad",
    "Rhythmic Soul",
    "Freestyle",
    "Duet",
    "Punk Rock",
    "Drum Solo",
    "A cappella",
    "Euro-House",
    "Dance Hall",
    "Goa music",
    "Drum & bass",
    "Club-house",
    "Hardcore techno",
    "Terror",
    "Indie",
    "Britpop",
    "Negerpunk",
    "Polsk punk",
    "Beat",
    "Christian gangsta rap",
    "Heavy metal",
    "Black metal",
    "Crossover",
    "Contemporary Christian",
    "Christian rock",
    "Merengue",
    "Salsa",
    "Thrash metal",
    "Anime",
    "Jpop",
    "Synthpop",
    "Christmas",
    "Art rock",
    "Baroque",
    "Bhangra",
    "Big beat",
    "Breakbeat",
    "Chillout",
    "Downtempo",
    "Dub",
    "EBM",
    "Eclectic",
    "Electro",
    "Electroclash",
    "Emo",
    "Experimental",
    "Garage",
    "Global",
    "IDM",
    "Illbient",
    "Industro-Goth",
    "Jam Band",
    "Krautrock",
    "Leftfield",
    "Lounge",
    "Math rock",
    "New romantic",
    "Nu-breakz",
    "Post-punk",
    "Post-rock",
    "Psytrance",
    "Shoegaze",
    "Space rock",
    "Trop rock",
    "World music",
    "Neoclassical",
    "Audiobook",
    "Audio theatre",
    "Neue Deutsche Welle",
    "Podcast",
    "Indie rock",
    "G-Funk",
    "Dubstep",
    "Garage rock",
    "Psybient",
];

pub fn get_genre(id: u8) -> Option<&'static str> {
    GENRES.get(id as usize).copied()
}

pub fn get_genre_id(genre: &str) -> Option<u8> {
    let id = match genre {
        "Blues" => 0,
        "Classic rock" => 1,
        "Country" => 2,
        "Dance" => 3,
        "Disco" => 4,
        "Funk" => 5,
        "Grunge" => 6,
        "Hip-hop" => 7,
        "Jazz" => 8,
        "Metal" => 9,
        "New age" => 10,
        "Oldies" => 11,
        "Other" => 12,
        "Pop" => 13,
        "Rhythm and blues" => 14,
        "Rap" => 15,
        "Reggae" => 16,
        "Rock" => 17,
        "Techno" => 18,
        "Industrial" => 19,
        "Alternative" => 20,
        "Ska" => 21,
        "Death metal" => 22,
        "Pranks" => 23,
        "Soundtrack" => 24,
        "Euro-techno" => 25,
        "Ambient" => 26,
        "Trip-hop" => 27,
        "Vocal" => 28,
        "Jazz & funk" => 29,
        "Fusion" => 30,
        "Trance" => 31,
        "Classical" => 32,
        "Instrumental" => 33,
        "Acid" => 34,
        "House" => 35,
        "Game" => 36,
        "Sound clip" => 37,
        "Gospel" => 38,
        "Noise" => 39,
        "Alternative rock" => 40,
        "Bass" => 41,
        "Soul" => 42,
        "Punk" => 43,
        "Space" => 44,
        "Meditative" => 45,
        "Instrumental pop" => 46,
        "Instrumental rock" => 47,
        "Ethnic" => 48,
        "Gothic" => 49,
        "Darkwave" => 50,
        "Techno-industrial" => 51,
        "Electronic" => 52,
        "Pop-folk" => 53,
        "Eurodance" => 54,
        "Dream" => 55,
        "Southern rock" => 56,
        "Comedy" => 57,
        "Cult" => 58,
        "Gangsta" => 59,
        "Top 40" => 60,
        "Christian rap" => 61,
        "Pop/funk" => 62,
        "Jungle music" => 63,
        "Native US" => 64,
        "Cabaret" => 65,
        "New wave" => 66,
        "Psychedelic" => 67,
        "Rave" => 68,
        "Showtunes" => 69,
        "Trailer" => 70,
        "Lo-fi" => 71,
        "Tribal" => 72,
        "Acid punk" => 73,
        "Acid jazz" => 74,
        "Polka" => 75,
        "Retro" => 76,
        "Musical" => 77,
        "Rock 'n' roll" => 78,
        "Hard rock" => 79,
        "Folk" => 80,
        "Folk rock" => 81,
        "National folk" => 82,
        "Swing" => 83,
        "Fast fusion" => 84,
        "Bebop" => 85,
        "Latin" => 86,
        "Revival" => 87,
        "Celtic" => 88,
        "Bluegrass" => 89,
        "Avantgarde" => 90,
        "Gothic rock" => 91,
        "Progressive rock" => 92,
        "Psychedelic rock" => 93,
        "Symphonic rock" => 94,
        "Slow rock" => 95,
        "Big band" => 96,
        "Chorus" => 97,
        "Easy listening" => 98,
        "Acoustic" => 99,
        "Humour" => 100,
        "Speech" => 101,
        "Chanson" => 102,
        "Opera" => 103,
        "Chamber music" => 104,
        "Sonata" => 105,
        "Symphony" => 106,
        "Booty bass" => 107,
        "Primus" => 108,
        "Porn groove" => 109,
        "Satire" => 110,
        "Slow jam" => 111,
        "Club" => 112,
        "Tango" => 113,
        "Samba" => 114,
        "Folklore" => 115,
        "Ballad" => 116,
        "Power ballad" => 117,
        "Rhythmic Soul" => 118,
        "Freestyle" => 119,
        "Duet" => 120,
        "Punk rock" => 121,
        "Drum solo" => 122,
        "A cappella" => 123,
        "Euro-house" => 124,
        "Dance hall" => 125,
        "Goa music" => 126,
        "Drum & bass" => 127,
        "Club-house" => 128,
        "Hardcore techno" => 129,
        "Terror" => 130,
        "Indie" => 131,
        "Britpop" => 132,
        "Negerpunk" => 133,
        "Polsk punk" => 134,
        "Beat" => 135,
        "Christian gangsta rap" => 136,
        "Heavy metal" => 137,
        "Black metal" => 138,
        "Crossover" => 139,
        "Contemporary Christian" => 140,
        "Christian rock" => 141,
        "Merengue" => 142,
        "Salsa" => 143,
        "Thrash metal" => 144,
        "Anime" => 145,
        "Jpop" => 146,
        "Synthpop" => 147,
        "Christmas" => 148,
        "Art rock" => 149,
        "Baroque" => 150,
        "Bhangra" => 151,
        "Big beat" => 152,
        "Breakbeat" => 153,
        "Chillout" => 154,
        "Downtempo" => 155,
        "Dub" => 156,
        "EBM" => 157,
        "Eclectic" => 158,
        "Electro" => 159,
        "Electroclash" => 160,
        "Emo" => 161,
        "Experimental" => 162,
        "Garage" => 163,
        "Global" => 164,
        "IDM" => 165,
        "Illbient" => 166,
        "Industro-Goth" => 167,
        "Jam band" => 168,
        "Krautrock" => 169,
        "Leftfield" => 170,
        "Lounge" => 171,
        "Math rock" => 172,
        "New romantic" => 173,
        "Nu-breakz" => 174,
        "Post-punk" => 175,
        "Post-rock" => 176,
        "Psytrance" => 177,
        "Shoegaze" => 178,
        "Space rock" => 179,
        "Trop rock" => 180,
        "World music" => 181,
        "Neoclassical" => 182,
        "Audiobook" => 183,
        "Audio theatre" => 184,
        "Neue Deutsche Welle" => 185,
        "Podcast" => 186,
        "Indie rock" => 187,
        "G-Funk" => 188,
        "Dubstep" => 189,
        "Garage rock" => 190,
        "Psybient" => 191,
        _ => return None,
    };
    Some(id)
}
